### ISSUE TITLE
data source on web admin throws and error

### ISSUE THREAD

**Issue by webdpro** [mikesprague/lucee5-heroku#4]
Hi,

When i installed it, everything went fine but going to the data source section between server and web throws an error, I can still get the data source in the server section but web errors out.

One other question I did have is, would it be possible to expand a little on the deployment side? When i try and deploy out it overwrites the settings each time, like its deploying a new instance of Lucee each time.

Thanks!

**Comment by mikesprague** [comment]
Heroku doesn't "remember" anything you change live on their side. This is known behavior no matter what type of app you are deploying there.

It is recommended to run your app locally with foreman, make any necessary changes there, and then deploy so that these changes will be there each time you app spins up. 

Regarding the datasource issue, that is more of a Lucee issue than an issue with this project. I suspect (although haven't confirmed) that working on your project locally and setting up datasources there may also remedy this. If you continue to have issues, you may also want to look into the "official" Lucee deployment pack for Heroku found here: https://github.com/lucee/lucee-heroku/

Hope that helps.
